// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopicSync.proto

#include "TopicSync.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR TopicSync::TopicSync(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.v_topic_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TopicSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TopicSyncDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TopicSyncDefaultTypeInternal() {}
  union {
    TopicSync _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TopicSyncDefaultTypeInternal _TopicSync_default_instance_;
static ::_pb::Metadata file_level_metadata_TopicSync_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_TopicSync_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_TopicSync_2eproto = nullptr;

const uint32_t TableStruct_TopicSync_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TopicSync, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TopicSync, _impl_.v_topic_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::TopicSync)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_TopicSync_default_instance_._instance,
};

const char descriptor_table_protodef_TopicSync_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017TopicSync.proto\"\034\n\tTopicSync\022\017\n\007v_topi"
  "c\030\001 \003(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_TopicSync_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_TopicSync_2eproto = {
    false, false, 55, descriptor_table_protodef_TopicSync_2eproto,
    "TopicSync.proto",
    &descriptor_table_TopicSync_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_TopicSync_2eproto::offsets,
    file_level_metadata_TopicSync_2eproto, file_level_enum_descriptors_TopicSync_2eproto,
    file_level_service_descriptors_TopicSync_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_TopicSync_2eproto_getter() {
  return &descriptor_table_TopicSync_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_TopicSync_2eproto(&descriptor_table_TopicSync_2eproto);

// ===================================================================

class TopicSync::_Internal {
 public:
};

TopicSync::TopicSync(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TopicSync)
}
TopicSync::TopicSync(const TopicSync& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TopicSync* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.v_topic_){from._impl_.v_topic_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:TopicSync)
}

inline void TopicSync::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.v_topic_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TopicSync::~TopicSync() {
  // @@protoc_insertion_point(destructor:TopicSync)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TopicSync::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.v_topic_.~RepeatedPtrField();
}

void TopicSync::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TopicSync::Clear() {
// @@protoc_insertion_point(message_clear_start:TopicSync)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.v_topic_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TopicSync::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string v_topic = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_v_topic();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "TopicSync.v_topic"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TopicSync::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TopicSync)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string v_topic = 1;
  for (int i = 0, n = this->_internal_v_topic_size(); i < n; i++) {
    const auto& s = this->_internal_v_topic(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TopicSync.v_topic");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TopicSync)
  return target;
}

size_t TopicSync::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TopicSync)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string v_topic = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.v_topic_.size());
  for (int i = 0, n = _impl_.v_topic_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.v_topic_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TopicSync::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TopicSync::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TopicSync::GetClassData() const { return &_class_data_; }


void TopicSync::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TopicSync*>(&to_msg);
  auto& from = static_cast<const TopicSync&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TopicSync)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.v_topic_.MergeFrom(from._impl_.v_topic_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TopicSync::CopyFrom(const TopicSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TopicSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TopicSync::IsInitialized() const {
  return true;
}

void TopicSync::InternalSwap(TopicSync* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.v_topic_.InternalSwap(&other->_impl_.v_topic_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TopicSync::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TopicSync_2eproto_getter, &descriptor_table_TopicSync_2eproto_once,
      file_level_metadata_TopicSync_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TopicSync*
Arena::CreateMaybeMessage< ::TopicSync >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TopicSync >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
